name: micromouse_project

services:
  ros-dev:
    build:
      context: .
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    container_name: micromouse_sim
    restart: unless-stopped

    volumes:
      - ./src:/home/ros/ros2_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./mazes:/home/ros/mazes
      - ./build_workspace.sh:/home/ros/ros2_ws/build_workspace.sh

    environment:
      - DISPLAY=host.docker.internal:0.0
      - QT_X11_NO_MITSHM=1

    command: tail -f /dev/null

    network_mode: host
